### ISSUE TITLE
如何修改侧边栏的图标

### ISSUE THREAD

**Issue by d1667018881** [Frost-ZX/frost-navigation#9]
能不能说一下怎么改侧边栏的图标😂

**Comment by Frost-ZX** [comment]
修改 `public/static/js/frostNavLinks.js` 中对应项的 `icon` 属性即可。
注：目前只能使用 [Element UI](https://element.eleme.cn/#/zh-CN/component/icon) 或 [Font Awesome 4.7](https://fontawesome.com/v4.7/icons/) 中存在的图标。
